# Generated by Django 4.1.2 on 2022-10-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slackUsername', models.CharField(max_length=20)),
                ('backend', models.BooleanField()),
                ('age', models.PositiveIntegerField(default=0)),
                ('bio', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
